import robloxpy.User.Internal as LocalUser
import robloxpy.Utils as Utils
def PrintData():
    print("UserID: " + str(LocalUser.UserID))
    print("Username: " + str(LocalUser.Username))
    print("Robux: " + str(LocalUser.Robux))
    print("Thumbnail: " + str(LocalUser.Thumbnail))
    print("isBuildersclub: " + str(LocalUser.isBuildersclub))
    print("isPremium: " + str(LocalUser.isPremium))
    print("canChangeUsername: " + str(LocalUser.canChangeUsername))
    print("isAdmin: " + str(LocalUser.isAdmin))
    print("isEmailOnFile: " + str(LocalUser.isEmailOnFile))
    print("isEmailVerified: " + str(LocalUser.isEmailVerified))
    print("isPhoneFeatureEnabled: " + str(LocalUser.isPhoneFeatureEnabled))
    print("isSuperSafePrivacyMode: " + str(LocalUser.isSuperSafePrivacyMode))
    print("IsAppChatSettingEnabled: " + str(LocalUser.IsAppChatSettingEnabled))
    print("IsGameChatSettingEnabled: " + str(LocalUser.IsGameChatSettingEnabled))
    print("IsContentRatingsSettingEnabled: " + str(LocalUser.IsContentRatingsSettingEnabled))
    print("IsParentalControlsTabEnabled: " + str(LocalUser.IsParentalControlsTabEnabled))
    print("IsSetPasswordNotificationEnabled: " + str(LocalUser.IsSetPasswordNotificationEnabled))
    print("ChangePasswordRequiresTwoStepVerification: " + str(LocalUser.ChangePasswordRequiresTwoStepVerification))
    print("ChangeEmailRequiresTwoStepVerification: " + str(LocalUser.ChangeEmailRequiresTwoStepVerification))
    print("UserEmail: " + str(LocalUser.UserEmail))
    print("UserEmailMasked: " + str(LocalUser.UserEmailMasked))
    print("UserEmailVerified: " + str(LocalUser.UserEmailVerified))
    print("CanHideInventory: " + str(LocalUser.CanHideInventory))
    print("CanTrade: " + str(LocalUser.CanTrade))
    print("MissingParentEmail: " + str(LocalUser.MissingParentEmail))
    print("IsUpdateEmailSectionShown: " + str(LocalUser.IsUpdateEmailSectionShown))
    print("IsUnder13UpdateEmailMessageSectionShown: " + str(LocalUser.IsUnder13UpdateEmailMessageSectionShown))
    print("IsUserConnectedToFacebook: " + str(LocalUser.IsUserConnectedToFacebook))
    print("IsTwoStepToggleEnabled: " + str(LocalUser.IsTwoStepToggleEnabled))
    print("AgeBracket: " + str(LocalUser.AgeBracket))
    print("UserAbove13: " + str(LocalUser.UserAbove13))
    print("ClientIpAddress: " + str(LocalUser.ClientIpAddress))
    print("UserAge: " + str(LocalUser.UserAge))
    print("IsBcRenewalMembership: " + str(LocalUser.IsBcRenewalMembership))
    print("IsAccountPinEnabled: " + str(LocalUser.IsAccountPinEnabled))
    print("IsAccountRestrictionsFeatureEnabled: " + str(LocalUser.IsAccountRestrictionsFeatureEnabled))
    print("IsAccountRestrictionsSettingEnabled: " + str(LocalUser.IsAccountRestrictionsSettingEnabled))
    print("IsAccountSettingsSocialNetworksV2Enabled: " + str(LocalUser.IsAccountSettingsSocialNetworksV2Enabled))
    print("InApp: " + str(LocalUser.InApp))
    print("HasFreeNameChange: " + str(LocalUser.HasFreeNameChange))
    print("IsAgeDownEnabled: " + str(LocalUser.IsAgeDownEnabled))
    print("ReceiveNewsletter: " + str(LocalUser.ReceiveNewsletter))

LocalUser.SetCookie("_|WARNING:-DO-NOT-SHARE-THIS.--Sharing-this-will-allow-someone-to-log-in-as-you-and-to-steal-your-ROBUX-and-items.|_77156070A5601FD00456FE2094CCCDA2F576511C49434C8E4BC9AAF5E8F14172C27AD5DF23E0FE33C293FACAD2AED7D00E63B695E5FA8BC1C56A0AC29D731A94094CFF281A9A968578F192FE5C14C79B35E61B571ABF95C6EB75177EE943724CB20ED1B0DF9F2535FD624FC6CC0147BAD1AFE36D96F6CC8C5C4485933DB5E4DAB6D28DD8EB458FC1B6B8CD03B5DDE053F41A64CD54B5C0D6D7312D83E7BAD16B38F8DF5E75DEA98CA3F7677AE9318DD328385EBCC783DEF5A4E68A5398C58A0E57CDAFFC66C02FFF6E0585218697A12531DCD026BC428CBBE96FF761AD07E362B9D62BE33B08968AE2034BDD31205D392E7DB659E048BAA5188EB75AD902830BA66883041A35A1F2688220FFF832173F2201DC000EE025DB8945C8BFA587E494CCC1C46B1EDB4794FC43768DB27BB80126211531")
print(Utils.TestCookie)
PrintData()